# Autogenerated wrapper script for Flavio_jll for aarch64-apple-darwin
export libflavioso

JLLWrappers.@generate_wrapper_header("Flavio")
JLLWrappers.@declare_library_product(libflavioso, "@rpath/libflavioso.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libflavioso,
        "lib/libflavioso.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
