# Autogenerated wrapper script for Flavio_jll for x86_64-w64-mingw32
export libflavioso

JLLWrappers.@generate_wrapper_header("Flavio")
JLLWrappers.@declare_library_product(libflavioso, "libflavioso.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libflavioso,
        "bin\\libflavioso.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
